name: time_management_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.1
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  google_sign_in: ^4.5.1
  localstorage: ^3.0.3+6
  provider: ^3.1.0
  shared_preferences: ^0.5.12+2
  uuid: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
