name: time_management_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  #Front-end dependencies

  #Back-end dependencies
  firebase_core: ^0.5.2
  firebase_auth: "^0.18.3"
  provider: ^3.1.0
  shared_preferences: ^0.5.12+2
  cloud_firestore: ^0.14.3
  google_sign_in: "^4.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
