name: time_management_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.1
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  google_sign_in: ^4.5.1
  localstorage: ^3.0.3+6
  oktoast: ^2.1.7
  provider: ^3.1.0
  uuid: 2.2.2
  email_validator: ^1.0.6
  skeleton_text: ^1.0.0
  #back-end dependencies
  firebase_messaging: "^8.0.0-dev.9"
dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.12+4

flutter:
  uses-material-design: true

  assets:
    - assets/
